language: python
python:
- '2.7'
install:
- bash deploy.sh -t master -h
before_install:
- openssl aes-256-cbc -K $encrypted_aa98fb4b6b61_key -iv $encrypted_aa98fb4b6b61_iv
  -in deploy.enc -out $HOME/.ssh/deploy -d
- chmod 600 $HOME/.ssh/deploy
